### ISSUE TITLE
WCRP- Competitor Limits Per Events

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#104]
Right now we have
> 5.2 If the competitor limit for a competition or an event is reached before the competition, the organization team must not approve any additional registrations for the competition or the event.
> 5.3 The competitor limit is per competition. Per day competitor limits are not allowed

5.2 would imply that comeptitor limits per event are allowed, while 5.3 would imply they are not allowed. One of these two should be fixed based on if we wish to allow them or not.

Just a side comment: if limits per event are allowed, I think that combining a competition comeptitor limit and limit per event would make sense (ie 100 competitors total, limit of 20 for fmc due to seating).

**Comment by cubewhiz** [comment]
5.2 indeed implies that event limits are permitted, so I think 5.3 is just an oversight--it was meant mostly to clarify that per day limits are no longer permitted.

I have a practical concern--how would per event limits be enforced? Our software does not currently support this.

**Comment by Jambrose777** [comment]
I don't think our software currently supports normal competitor limits. It is manual checking from what I know.

**Comment by DanielEgdal** [comment]
I suggest the following:

> The competitor limit is per competition **or per event**. Per day competitor limits are not allowed

Then it should be clear.

**Comment by cubewhiz** [comment]
Fixed via #117
