### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-documents#106]
I'm going to be leading an effort to create a Code of Conduct for the WCA. I have the following rough outline in mind, although I expect that we will need to be adapt it to WCA needs:

- Behaviour
  - We want a community that is welcoming and safe for everyone.
  - Specify what constitutes welcoming behaviour, and what does not.
- Processes
  - If anyone reports that something/someone is making them feel unwelcome in the community, we will take it seriously and take actions to address it.
  - If someone is making others feel unwelcome in the WCA Community through *any* kind of actions:
    - We will ask them to be aware of the impact of their actions and change their behaviour.
    - Beyond a certain threshold, they will be banned from WCA activities (e.g. online forum participation, attending competitions).

At the moment, I'm scheduling a video meeting with members of the WRC, WAC, WDC, and WEC to assemble the team responsible for this. We may draft an initial revision in private, but I want to make sure there is time for public feedback before we finalize anything.

**Comment by lgarron** [comment]
Agenda draft (feel free to offer revisions):

- 15min: Introductions, talk about WCA background and experience with e.g. diversity & inclusion
- 15min: Overall planning structure/timeline
- 15min: Brainstorm priorities
- 15min: decide on responsibilities and follow-up tasks, such as:
  - Assessing other examples of code of conduct

**Comment by Burnsy101** [comment]
@lgarron, I just would like quickly say that banning people from online WCA activities is much harder than it seems - on anonymous forums, people can constantly create alternative accounts and even on facebook groups where peoples names are known, if multiple people are involved in some sort of harassment they can relatively easily add each other to the forums, with complete bans often being hard to issue. It would also be impossible to moderate private messages, of which a portion of harassment occurs.

As well there are many non english forums which the predominantly english WCA staff might find it harder to access (as an example, ukraine has its own forums which could be difficult for the WRC to access as there are no ukrainina members) which could tamper things

overall, I think this is a fantastic idea, but banning people from online cubing activities is really hard and I think it is important for that to be understood

**Comment by Burnsy101** [comment]
one more thing - if someone is being harrassed now with regards to cubing, who in the WCA should they contact?

**Comment by lgarron** [comment]
> @lgarron, I just would like quickly say that banning people from online WCA activities is much harder than it seems

Indeed, this is not easy. But we need to have a clear plan for this as part of implementing a Code of Conduct.

> one more thing - if someone is being harrassed now with regards to cubing, who in the WCA should they contact?

The WDC.

**Comment by cubewhiz** [comment]
A Code of Conduct has already been drafted and published, so I'm closing this issue.
