### ISSUE TITLE
WCRP, Event Additions

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#113]
WCAT discussed to have more transparency added regarding when we allow event additions. We came with the following suggestion:

> 7.4 An additional event may be added upon the WCA Delegate's request at the discretion of the WCAT. The competition must meet the following requirements for an additional event to be added:
>> 7.4.1 The competition is at least 7 days away.
>> 7.4.2 A registration period for the competition must have a minimum of 72 hours before it closes.
>> 7.4.3 The competitor limit must not be completely filled.

Background: This gives more fairness to the competitors who may have originally not registered for a competition due to the event list.

**Comment by cubewhiz** [comment]
yes, I like this

**Comment by cubewhiz** [comment]
Fixed via #117
