### ISSUE TITLE
WCRP, Competitor Limits per Location for 3x3x3 Fewest Moves simultaneous competitions

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#116]
When announcing competitions, WCAT has been requiring a limit per location as opposed to per competition. A clause in the WCRP should be added to actually reflect what is going on.
I suggest: 

> 5.3.1 For 3x3x3 Fewest Moves simultaneous competitions, a competitor limit will be set per location, as opposed to the entire competition.

**Comment by cubewhiz** [comment]
I'm not happy with the wording. How about:

> 5.3.1 Exception: for 3x3x3 Fewest Moves simultaneous competitions, the competitor limit is per location.

**Comment by DanielEgdal** [comment]
(This was updated when requested. Commenting for bookkeeping).

**Comment by cubewhiz** [comment]
Fixed via #117
