### ISSUE TITLE
WCRP, Waiting lists

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#118]
As been outlined on certain threads, it is too different with how waiting lists are handled and it is not clear what policies are followed at different competitions. I see two solutions:

- Ask all competitions to set a deadline for the last possible time to be added to the list of accepted competitors, if you are on the waiting list. As a default, this would be once registration closes, but may be longer than that.
- For all competitions, simply just not allow waiting lists lasting longer than once that registration has closed.

**Comment by DanielEgdal** [comment]
I'm going with the first option for now. Please come with feedback:

> 6.2.3 The organization team must outline the conditions of the waiting list, and if one is in place.
> > 6.2.3.1 If a waiting list is in place:
> > > 6.2.3.1.1 Registrants will be placed on the waiting list if they have completed all requirements for a valid registration, but the competitor limit has been filled.
> > > 6.2.3.1.2. it must be stated what the deadline is to be accepted if you are on the waiting list. 
> > > 6.2.3.1.2.1 This deadline should be the same as deadline for refunds for competitors canceling their registration, if (partial) refunds are to be given.

> > 6.2.3.2 If a waiting list is not in place, the Delegate should inform the WCAT once the competitor limit has been filled so the registration period can be closed.

**Comment by pokekrom** [comment]
Could we set a size for the waiting list? Some competitions know that competitors who are beyond spot #X will never make it to the competitor list. Once this limit is reached, registration is closed and all the competitors on the "successful waitinglist" can be allowed to compete (if a spot gets free).

**Comment by cubewhiz** [comment]
I would expect so. We should clarify this.

**Comment by DanielEgdal** [comment]
Added 6.2.4.1.3 which should clarify it.

**Comment by pokekrom** [comment]
And it sounds like a possible Software implementation for the future!
Thanks Daniel.

**Comment by cubewhiz** [comment]
Fixed via #117
