### ISSUE TITLE
WCRP, Deadlines for registration updates

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-documents#119]
It is often not clear which competitions allow event additions after registration has officially closed. It should be stated in the registration requirements when the deadline is to edit your registered events.

My proposal:

> 6.3 The deadline for updating registered events for competitors with completed registrations must be outlined.
> > 6.3.1 This deadline will either be at the same time as registration closes or after registration has closed.
> > > 6.3.1.1 The deadline may be set to be just before an event is scheduled to take place. 

> > 6.3.2 Competitors may choose not to compete in an event they are registered for.

**Comment by pokekrom** [comment]
It could be clearer that these changes can be allowed until the beginning of an event (the first or last group).
Ideally, WCA Live should be aware of that and it would **not** allow the scoretaker to add competitors on the day (there is a function for it currently).

**Comment by cubewhiz** [comment]
SGTM

**Comment by DanielEgdal** [comment]
@pokekrom I added 6.2.3.1.1 to clarify that.

**Comment by cubewhiz** [comment]
Fixed via #117
