### ISSUE TITLE
WCRP, require Delegates to show the Regulations copy if the competitor request it

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-documents#127]
(Based on comments of [#874](https://github.com/thewca/wca-regulations/issues/874))

The idea is to require the Delegate to show a copy of Regulations during a dispute if the competitor claims it. Copy of the conversation:

> IMO actually the reg should also allow the competitor to access said copy of the reg in the event that the competitor needs to dispute a ruling based on the regs. It is fair sportsmanship to for the delegate to do that though, so not sure if it has to be a reg.

> There is nothing that wouldn't allow competitors to have a copy of the Regulations.

>> There is nothing that wouldn't allow competitors to have a copy of the Regulations.
>
> Other than not having access to a device that can access the Internet at home or during a competition?

>>> There is nothing that wouldn't allow competitors to have a copy of the Regulations.
>
>> Other than not having access to a device that can access the Internet at home or during a competition?
>
> Competitors can bring printed copies of Regulations if they wish. So not having Internet access shouldn't be a problem. And if they don't have any copy (printed or Internet), there shouldn't be any problem as Delegate is required to do it.

> @Ivan-Brigidano I think the problem we are trying to address here is that the Delegate should not be allowed to withhold information about the regs front the competitor, especially if there is a dispute.

**Comment by Ivan-Brigidano** [comment]
From my point of view I think this is arguably a good addition for the WCRP. However, Delegates are supposed to be trusted and experienced competitors, so really it isn't that necessary.

**Comment by cubewhiz** [comment]
If anything, I feel this belongs better a a guideline in the Regs than in the WCRP. Perhaps it can be a guideline for handling incidents at competitions?

**Comment by Ivan-Brigidano** [comment]
> If anything, I feel this belongs better a a guideline in the Regs than in the WCRP. Perhaps it can be a guideline for handling incidents at competitions?

Not sure if this should be a guideline. But it could be a part of a hypothetical guide/policy to Delegates for handling common incidents.

**Comment by cubewhiz** [comment]
That's fine, too. Either way, I don't think it belongs in _this_ policy, so I'm closing this thread.
