### ISSUE TITLE
WCRP - Allow Registered Speedcuber Status as Qualification requirement

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-documents#129]
Currently the wording of 5.1.1 of the WCRP means that if a qualification requirement is used, it can only be used on a per-event basis. I get this - we shouldn't require a certain result in 4x4x4 Cube in order to compete in Megaminx for example. However I feel there should be an exception to this, in requiring the competitor to be a registered speedcuber.

Having such a requirement would present considerable logistical advantages for medium sized championships - no new competitor tutorial, less A7g - while not requiring results in events held less frequently in that region.

I would suggest wording such as:

> 5.1.1.1 Exception: A qualification standard of being a registered speedcuber may be used

**Comment by Ivan-Brigidano** [comment]
Maybe is arguable for a Championship, but for non-Championship, I think this shouldn't be an option because isn't really in line with WCA Mission:

> The Mission of the World Cube Association is to have more competitions in more countries with **more people** and more fun, under fair and equal conditions.

**Comment by EdHollingdale** [comment]
@Ivan-Brigidano I agree this should only be used for championships or competitions of similar size/scope. The same view could be said for all qualification requirements being against the WCA mission. Since any such requirements need WCAT approval I think I can trust them to only permit them for championships or other large competitions.

**Comment by cubewhiz** [comment]
I don't think this is very useful. Other than some rare cases, I can't think of how this provides any more advantage than just a loose qualification requirement in a specific event. Is the concern that a competitor may not have had access to certain events so they won't have any results in them?

**Comment by EdHollingdale** [comment]
@cubewhiz that is the concern. You can set lose requirements but these still require you having competed in the event. For “medium” championships one of the benefits is that it allows competitors to compete in events that are not held as frequently in that region. E.g. a competitor who has been to 3 one-day competitions and never competed in 5x5 should be allowed to do so, but organisers may not want to run the risk of first-timers signing up and competing in just 5x5.

**Comment by cubewhiz** [comment]
Sorry, I'm still not convinced that this is worth the hassle. It seems like such a rare case that there are other ways to cater to this situation without making the policy more complicated than it is already.

**Comment by cubewhiz** [comment]
I'm closing this as I don't think this is necessary at this time.
