### ISSUE TITLE
Where did our GITHUB_TOKEN come from?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-documents#13]
I looked at the list of personal access tokens for thewca-bot (https://github.com/settings/tokens), and I didn't see anything specifically for this repo. @jonatanklosko, do you know how you generated this token? Is it possible you created a token on your personal github account? Or maybe reused one of the existing tokens on thewca-bot?

I think it would make sense to instead use a token dedicated to wca-documents, so I went ahead and generated one for this project. I'll send in a PR switching this repo to use it.

**Comment by jonatanklosko** [comment]
There's no way to generate tokens for organizations, so I generated a new token for my account. Obviously I forgot that we have a more appropriate account in the form of @thewca-bot to do so! Thanks for setting it up :tada:
