### ISSUE TITLE
Standardize Open Elections for WCA Board

### ISSUE THREAD

**Issue by ccbaird** [thewca/wca-documents#130]
There should be an open standard for community involvement in electing the WCA Board. To that end I propose the following:

Five Board members will be elected to one-year terms at an election held each November, with installment of new members to occur at the beginning of the annual meeting held in December of the same year. 

All community members will have the right to vote on Board members, as follows:
- 1 vote for every competition at which the individual recorded an official result other than a DNS in the year ending October 15th
OR
- 3 votes for each official WCA competition at which the individual served as an official organizer in the year ending October 15th
OR
6 votes for each official WCA competition for which the individual served as an official delegate in the year ending October 15th
AND
- 10 votes for serving in an official capacity with the WCA outside of competitions (Board, WRC, etc.)

To be eligible to serve on the board of directors an individual must meet all of the following criteria:
- Nominated for the position by October 1st of the current year (including self-nominated)
- At least 21 years of age by December 1st of the current year
- Pass a criminal background check
- Not serving a ban or suspension imposed by the WDC
- Eligible under the above criteria to cast at least 25 votes for Board members

**Comment by EdHollingdale** [comment]
I think the current election procedures are sufficient. They use a similar system to what you have described. 
0 votes for competitors and organisers
1 vote for delegates if they have been promoted to full delegate
1 vote for WCA team/committee members if they have been promoted to senior member

The WCA is not a democracy, and it is not a democracy for a reason.

**Comment by ccbaird** [comment]
The WCA as you describe it is a good-ol’-boys-club. It doesn’t need to be a democracy, I am proposing something in between.

**Comment by UnderwaterCuber** [comment]
So you want to change it from a well thought out process where people are judged on their merits, into a popularity contest? 

Also you do realize how few applications there are to become board members? It’s a lot of work with no financial compensation.

**Comment by ccbaird** [comment]
@UnderwaterCuber I want to change it from cronyism to something with some accountability. The makeup of the board wouldn’t even necessarily have to change, but it should be in some limited way answerable to the community. In order for there to be that accountability there would have to be the possibility of a change in the membership of the board.

**Comment by UnderwaterCuber** [comment]
> @UnderwaterCuber I want to change it from cronyism to something with some accountability. The makeup of the board wouldn’t even necessarily have to change, but it should be in some limited way answerable to the community. In order for there to be that accountability there would have to be the possibility of a change in the membership of the board.

How is it “cronyism”? Any why should the board be answerable to the community? Anytime a decision was made that people didn’t like they would just create an online lynch mob and remove wca staff to retaliate.

**Comment by cubewhiz** [comment]
Before you waste too much time on your idea, I will let you know that I do not support it at all. I think the processes in place for electing Board members are sufficient and I insist that decisions will remain as the results of Board votes--community input may be taken into consideration, but will not have any binding impact on any decision. Changing the current process for electing Board members or how votes are decided would require a change to the Motions. Any change to the Motions requires unanimous support from the Board, so there is no chance that this will be considered. This is not up for debate so I am closing this issue.
