### ISSUE TITLE
Small grammatical edit in WQAC's Motion

### ISSUE THREAD

**Issue by UnderwaterCuber** [thewca/wca-documents#131]
WQAC's Motion currently reads

> 1.1 Promoting awareness and enforcing application of these standards among WCA Staff,
Regional Organizations, Competition Organizers, and Competition Staff.

should be updated to 

> 1.1 Promoting awareness and enforcing the application of these standards among WCA Staff,
Regional Organizations, Competition Organizers, and Competition Staff.

**Comment by ccbaird** [comment]
How does adding a definite article there change the meaning in any way? I agree clarity is important, and it’s not incorrect to have it there, but I don’t think it affects anything.

**Comment by cubewhiz** [comment]
Because this was not a necessary change and the definition was already clear, we opted not to make this change.
