### ISSUE TITLE
Motion 10.2020.1 (WEAT) isn't showing up on the WCA website

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-documents#144]
_10.2020.1 - Executive Assistants Team_ currently isn't showing up here on this page:
https://www.worldcubeassociation.org/documents

![Screenshot 2020-01-30 12 36 32](https://user-images.githubusercontent.com/5139750/73474873-2f220680-435d-11ea-8248-9e619e2dfcd6.png)

I suspect it has something to do with the document missing the **.md** extension here: https://github.com/thewca/wca-documents/blob/master/documents/motions/10.2020.1%20-%20Executive%20Assistants%20Team.

**Comment by cubewhiz** [comment]
Yep, that's precisely what happened. WCT noticed it wasn't showing up last night and we figured it out this morning, but I haven't had time to fix it until now. Thanks!
