### ISSUE TITLE
WCSP - Clarify what "own cover" refers to

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-documents#164]
The WCA Competition Safety Policy states that:
> 2.4 Competitors may bring their own cover to place over the competition supplied mat or timer provided the function of the equipment is not affected.
> 2.4.1 Competitors are responsible for any modifications made to timing equipment and will not be eligible for any extra attempts if the function of the equipment is affected by the competitor’s cover.

The WCA Regulations Committee originally interpreted the term "own cover" as a "cover" (commonly known as "cube cover" or "puzzle cover") that is used in the WCA Regulations and Guidelines. But according to the Board, this should be interpreted the following way:
> (...) allowing the competitor to place cling wrap (or something similar) over the mat or timer so that they do not need to physically touch the timer or mat (and they would discard the cover at the end of their attempts).

Therefore, the WRC suggests using a different term or to clarify what "cover" means on these articles.

**Comment by cubewhiz** [comment]
How about a "covering"? Wrapping? Sheathing?

**Comment by c-goodyear** [comment]
Changing 2.4 to read something like:

> 2.4 Competitors may bring their own cover **(e.g. clear plastic)** to place over the competition supplied mat or timer provided the function of the equipment is not affected.

would probably make most sense, and be easy to read instead of using words that may be out of vocabulary for a lot of non-native speakers.

**Comment by cubewhiz** [comment]
Sure, I think this is reasonable.

**Comment by Ivan-Brigidano** [comment]
Maybe "sheet"? I'm not sure if this term would make sense for native English speakers though.
> 2.4 Competitors may bring their own **sheet (e.g. clear plastic)** to place over the competition supplied mat or timer provided the function of the equipment is not affected.

**Comment by c-goodyear** [comment]
Sheet excludes some options that people may want to take with such a cover. Maybe they are fine touching the timer pads, because they can be disinfected easily. But the mats are harder to disinfect because they are absorbent, so allowing a competitor to bring something to cover the mat which isn't a sheet - such as a cloth - needs to not be excluded by the wording.

**Comment by cubewhiz** [comment]
Agree with Callum here. Perhaps leaving as cover with the clarification makes the most sense.
