### ISSUE TITLE
'WCA Board of Directors' and 'Board of Directors' are both used in motions

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#194]
Both 'WCA Board of Directors' and 'Board of Directors' are used in the exact same manner. Since it isn't imperative, I would recommend adjusting all of these to one use or the other in the next motions update.

**Comment by Jambrose777** [comment]
An example would be in the Senior Delegates motion: 

> 8. Senior Delegates can demote Regional Delegates to Full Delegates in their attributed area with approval from the Board of Directors.

and 

> 1. If a region of Delegates does not have an assigned Senior Delegate the WCA Board of Directors will assume the responsibilities of a Senior Delegate in that region.

**Comment by Epride** [comment]
Thanks for bringing this up!

We will handle it in the next amendment series

**Comment by cubewhiz** [comment]
I think Ethan took care of all instances of this, so I'm closing this issue.
