### ISSUE TITLE
Bylaws Formatting

### ISSUE THREAD

**Issue by saranshgrover** [thewca/wca-documents#197]
The newest Bylaws pdf has formatting issues in `2.10 Annual Meetings`. Seems like it is happening due to it being in 2 separate pages. Formatting is fine in the markdown. @jonatanklosko would you know what might be causing this?

![image](https://user-images.githubusercontent.com/24918614/95802338-34489b00-0ccb-11eb-8321-464d3345da4f.png)

**Comment by denthebro** [comment]
I tried fixing the issue through the markdown file itself in this pull request: https://github.com/thewca/wca-documents/pull/207
Just added a page break

**Comment by Nevseros** [comment]
@thewca/software-team Can you please close this one? It was resolved.

**Comment by notrichardpeng** [comment]
sure :)
