### ISSUE TITLE
Safety Policy: add a right to cancel competition to Board

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-documents#198]
Recently two competitions in Russia were cancelled by WCA Board because the COVID stats in Russia is bad. It is not indicated now in Safety Policy that Board have a right to cancel the competition and organizers waited for cancellation from local governments but was not ready that Board can cancel the competition. One competition even have the post in social network group that "competition will be with 100% chance" one day before cancellation.

So I think that it should be indicated straight in the policy.

**Comment by EdHollingdale** [comment]
The Board and the WCAT leader have the right to cancel competitions even in "normal" times - e.g. see the WCAT motion 2.3.1.

**Comment by AlexKatyukov** [comment]
Ed,

I think this improvement is not about "give an opportunity to Board" — not all organizers read all motions and this is okay. I read all motions once where I was too bored. I think that WCRP and Safety Policy should be enough.

**Comment by Epride** [comment]
This has been addressed in V1.3 see #203
