### ISSUE TITLE
Are we sure we want to put all environment variables in our Repository settings?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-documents#2]
I was trying to find out where `WCA_HOST` (used in deploy.sh) is defined, and it took me a while to find that it's defined over in https://travis-ci.org/thewca/wca-documents/settings. What's even weirder is that I can't actually see the value of the variable, it's just some dots:

![image](https://user-images.githubusercontent.com/277474/44415748-08d02880-a526-11e8-83b7-d6fdbbc1456f.png)

I'd argue that this is perfectly safe to put in our `.travis.yml` file.

https://docs.travis-ci.com/user/environment-variables/ has some advice about where to put environment variables, and I feel like `$WCA_HOST` falls under the category of "if it does not contain sensitive information, might be different for different branches and should be available to forks – add it to your .travis.yml".

**Comment by jonatanklosko** [comment]
I extracted it as a variable in case we want to test things on the staging first (e.g. deployment changes). That's what I did before this went live - set it to staging.worldcubeassociation.org

It may make sense to make this env variable visible under settings (when adding an new one you can make it hidden or visible).
