### ISSUE TITLE
Delegate Crash Course - Internal Anchors Do not work

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#211]
When clicking "(see Administering registration data)" on the Delegate Crash Course it will open this. https://www.worldcubeassociation.org/edudoc/delegate-crash-course/delegate_crash_course.pdf#administering-registration-data
This no longer directs you directly to the correct section. We should either remove these anchors or have them working again.

**Comment by cubewhiz** [comment]
In a quick scan, I only found two of these. We should just remove them (I think most were already removed, but these were just missed).

**Comment by Jambrose777** [comment]
Works for me! (and is an easier solution I think) Submitted a PR for it.
