### ISSUE TITLE
WCRP numbering issue

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#227]
On the WCRP, point 11 should be a sub point of 10.
![image](https://user-images.githubusercontent.com/11577241/112791186-f4822f80-902e-11eb-9928-be92b37022f7.png)

It seems like this is set up correctly in the .md file, so I'm not too sure why it has the number/tabbing wrong.
![image](https://user-images.githubusercontent.com/11577241/112791224-0e237700-902f-11eb-9dcb-2f155fc20a84.png)

**Comment by emattos1723** [comment]
Adding an extra space before the 1. seems to fix it, though I don't know why this one requires 4 instead of 3 like all the others.
