### ISSUE TITLE
Typos in motions

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/wca-documents#247]
Typos are found in the Disciplinary Committee and Suspensions and other Sanctions motions.

Please refer to this commit: https://github.com/JonEsparaz/wca-documents/commit/084d1e92a1af757cfc6dea90c391ade7ba288787

**Comment by gregorbg** [comment]
Just adding a note here why we don't fix those typos immediately: At the present date, the Board is uncertain whether clerical errors can be corrected without a full formal Motions Update process and vote.

We will most likely resolve this issue by adding a clause to the Motions and Bylaws that clerical errors may be fixed without a vote the next time we hold an actual vote. This will happen in a few months when enough change requests have accumulated to warrant triggering a full Motions Update process.

**Comment by c-goodyear** [comment]
Fixed in #300
