### ISSUE TITLE
Term Extensions

### ISSUE THREAD

**Issue by cubewhiz** [thewca/wca-documents#250]
The Motions say that terms for Senior Delegates and Team Leaders may be extended for up to two years, but they are unclear about whether that is a cumulative amount (two years total), or if extensions may be granted for up to two years at a time, but as many times as the Board wishes. The Board has been using the former interpretation, and has been asking Seniors and Team Leaders who have been extended for two years already to reapply if they wish to stay in the role. This should be clarified in the next Motions update.

**Comment by Nevseros** [comment]
Isn't there the same issue for Council Leaders?

**Comment by c-goodyear** [comment]
Fixed in #300
