### ISSUE TITLE
WCA Championship Hosts Motion

### ISSUE THREAD

**Issue by Epride** [thewca/wca-documents#256]
In order to improve the governance of the WCA the Board has decided to implement a motion regarding how the host cities of championship events are awarded. While the process is fairly well defined it should be documented in line with other WCA processes. This will be included in the next motions amendments

**Comment by Ivan-Brigidano** [comment]
Will this include National Championships?

**Comment by Epride** [comment]
If anything it would only include a line similar to 9.6 of the WCA Competition Requirements Policy but nothing more as the WCA does not have any involvement in the selection of location of National Championships.

**Comment by c-goodyear** [comment]
Fixed in #300
