### ISSUE TITLE
Wrong article reference in "Amendments of Regulations" motion

### ISSUE THREAD

**Issue by Niksson** [thewca/wca-documents#277]
The current version of "Amendments of Regulations" motion states:

`2. Amendments consisting of changes that are urgent and/or corrections of clerical errors may be processed as an update of the Regulations and can be handed over to the WCA Board directly, without the process described in Article 2 of this Motion.`

However, the process of amendment is described in Article 1, not Article 2.

I suppose that this is just a typo.

**Comment by c-goodyear** [comment]
Fixed in #300
