### ISSUE TITLE
Is it possible to simplify the way we store our private key?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-documents#3]
This is somewhat related to #2, but I wanted to file a separate issue to discuss it.

Currently, it looks like we have a `.travis/deploy_rsa.enc` file that we encrypted offline using `openssl`, and then committed to our repository. Then, when travis runs, it needs to decrypt that file, but to decrypt that file, it needs a secret! So, we put *that* secret over in our repository settings (https://travis-ci.org/thewca/wca-documents/settings).

Can we avoid the double decrypt here and instead store the encrypted version of `.travis/deploy_rsa.enc` directly in our `.travis.yml` as an encrypted environment variable (https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)? That way, travis will handle the decrypting for us, which feels simpler to me.

**Comment by jonatanklosko** [comment]
I thought of the current flow as complex at first, but as far as I remember that's what I found people do. After having it done, it now looks quite simple and reasonable, especially that Travis offers a script that encrypts a file, updates .travis.yml with decryption code, and adds those secret env vars.

I'm not entirely sure what you suggest here. Is it that we should store file content as env variable and create a file out of it during the build?

**Comment by jfly** [comment]
> Is it that we should store file content as env variable

That's exactly what I'm thinking. I think of it like this: Travis gives us the ability to store a secret. That's like having a secure bank vault where we can put stuff. Say I've got a special time cube I want to keep safe. I could put it in Travis's secure bank vault and be done with it. However, what we've done here is to build a whole *new* vault, and taken the key to open that vault, and put it in Travis's bank vault. Now, when we need our cube, we have to go to Travis, get our key, and then go open our own bank vault to get the cube.

> and create a file out of it during the build?

Actually, I think we'd be able to avoid creating a temp variable entirely by changing `deploy.sh` a bit to use bash's fun "create me a temp file" construct:

```
...
ssh-add <(echo $PRIVATE_KEY)
...
```

(This may run into silly permission checking issues and we may have to create a temp file anyways.)

**Comment by jonatanklosko** [comment]
For the record, I found some guys describing it [here](https://github.com/wp-cli/wp-cli/issues/3798) and implementing [here](https://github.com/wp-cli/wp-cli/pull/3799/files#diff-b9950ba654fc2316e1e533194cfa0184), although it doesn't seem popular.

**Comment by jfly** [comment]
I looked into this, and now I know why people don't do it this way! If you generate a large enough key (in this case, I generated one with 4096 bits), `travis encrypt` will tell you to use `travis encrypt-file` instead.

```
➜  ~/gitting/wca-documents git:(move-some-env-vars-into-travis.yml-file) ✗ travis encrypt --add < .travis/deploy_rsa
data too large - consider using travis encrypt-file or travis env set
```

So, this seems fine to me.
