### ISSUE TITLE
Crash Course: Update Recommending a Delegate Section

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-documents#344]
The "Recommending a Delegate" section of the crash course is out of date. It does not factor in Trainee Delegates, nor the fact that in many areas Regional Delegates handle some of these tasks not the Senior. We will also now not be suggesting new trainee delegates email all delegates with an introduction, only the Board and delegates within their region.

**Comment by dmint789** [comment]
There is a lot on there that is out of date. We plan to remake the delegate crash course soon, since we have many more members now.
