### ISSUE TITLE
Broken links for some documents

### ISSUE THREAD

**Issue by Nanush7** [thewca/wca-documents#376]
`wca{...}` is always replaced with the www subdomain, but in some cases it needs to be replaced with the documents subdomain. Maybe the script can check if the url includes "documents/" and then decide which one to use? (this way we don't need to change every single file where `wca{...}` is used).

The list of files using this shortcut:
```
$ grep -R --files-with-matches "wca{"
./documents-guide.md
./bin/build.sh
./README.md
./documents/motions/10.2021.6 - Financial Committee.md
./documents/motions/07.2021.1 - Registered Speedcubers.md
./documents/motions/01.2021.1 - Spirit.md
./documents/motions/04.2022.1 - WCA Board.md
./documents/motions/10.2021.2 - Competition Announcement Team.md
./documents/motions/19.2021.1 - Regulations and Guidelines.md
./documents/motions/10.2021.9 - Regulations Committee.md
./documents/motions/10.2022.3 - Disciplinary Committee.md
./documents/policies/external/Competition Requirements.md
./documents/policies/external/Logo Usage.md
./documents/Code of Ethics.md
```

**Comment by dmint789** [comment]
What do you mean by the documents subdomain?

**Comment by dmint789** [comment]
Is there really a documents.worldcubeassociation.org?

**Comment by dmint789** [comment]
@Nanush7 the link works for me though

**Comment by Nanush7** [comment]
Which one?

**Comment by dmint789** [comment]
@Nanush7 the one you just sent for the WSAP

**Comment by Nanush7** [comment]
Yeah, the www doesn't work anymore for documents.

**Comment by dmint789** [comment]
Oh, I thought you were sharing a link that IS broken. Yeah, this needs to be fixed then.
