### ISSUE TITLE
Document titles showing unrendered styling text in browser

### ISSUE THREAD

**Issue by nsilvestri** [thewca/wca-documents#398]
Repro:

1. Visit https://documents.worldcubeassociation.org/documents/minutes/2022-10-08%20WCA%20Annual%20Meeting.pdf in browser (Firefox and Chrome have similar but slightly different issues)
2. The tab title is `::::: {.text-center} - 2022-10-08 WCA Annual Meeting.pdf` on Firefox and `::::: {.text-center}` on Chrome. Neither are correct

**Comment by dmint789** [comment]
Oh gosh, it must be the recent update that affected this. I did not anticipate the tab title changing 😅
