### ISSUE TITLE
Require a website for Regional Organizations to be acknowledged

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-documents#44]
We should add this requirement in 3.2 of [Regional Organizations Motion](https://github.com/thewca/wca-documents/blob/master/documents/motions/06.2019.1%20-%20Regional%20Organizations.md).

**Comment by AlbertoPdRF** [comment]
Jeremy suggested [here](https://github.com/thewca/worldcubeassociation.org/pull/3772#discussion_r244900216) that we require Regional Organizations to run their websites on HTTPS. I'm fine with that!

**Comment by jfly** [comment]
> What is the reason to require organizations to run their websites on HTTPS? -@cubewhiz

I think it is in the best interest of our members that our regional organizations serve their webpages over a secure channel. Nowadays, it is easy and free to get a HTTPS certificate, so there's no good reason for people *not* to. I'd be ok with us strongly encouraging people to use HTTPS instead of requiring it, though. Sort of a "if you're not using HTTPS, you must have a really good reason not to". CC-ing @lgarron as he knows more about this than me.

**Comment by lgarron** [comment]
Sites with HTTP instead of HTTPS show as "Not Secure" in Chrome.



> Sort of a "if you're not using HTTPS, you must have a really good reason not to".

**Comment by lgarron** [comment]
> Sort of a "if you're not using HTTPS, you must have a really good reason not to".

Indeed. It's free and easier than ever with many hosting providers now to provide the baseline security of HTTPS. There is no reason for a new site not to be HTTPS, and very few "legacy" sites have a legitimate reason to avoid going full HTTPS.

- https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/
- https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
- https://doesmysiteneedhttps.com/
- https://whytls.com/

> I'd be ok with us strongly encouraging people to use HTTPS instead of requiring it, though.

I'd prefer to require it, but I'm fine with making well-considered (and rare) exceptions.

The most common excuse will probably be "my hosting provider doesn't make it easy", at which point we need to decide whether to accept that excuse. I'd say it's time to pressure or ditch such hosting providers, but sometimes there are annoying circumstances that can make it an annoying use of time to move old sites.

(There are good, reliable, free hosting providers that should work well for competition sites. For example, GitHub Pages works very well for serving static content. Disclosure: Maintaining GH Pages is currently part of my day job. :-D)

**Comment by lgarron** [comment]
I also want to mention: external sites handling private competitor data should *absolutely* be required HTTPS – but that's only a small part of responsibilities like the GDPR.
