### ISSUE TITLE
Remove Example Proximity Exception

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#48]
Remove this line from the Competition Proximity Policy as it is not an (strong) argument that is acceptable for a proximity collision exception

> c. In the last 12 months, there have been fewer than 16 competitions in the area 100 km around the competition.

or change 16 to a more reasonable number like 8 (WCAT opinion).

**Comment by AlbertoPdRF** [comment]
Ups, this should have been closed with #52!
