### ISSUE TITLE
A textual revision of the Motions is needed.

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-documents#5]
Things to change:

- In [16.2017.1](https://github.com/thewca/wca-documents/blob/master/documents/motions/16.2017.1%20-%20Disputes.md) it says "Ethical Committee" when the official name is "Ethics Committee".
- In [8.2018.1](https://github.com/thewca/wca-documents/blob/master/documents/motions/08.2018.1%20-%20Delegates.md) it was introduced "with copy to the WCA Board" but should it be "with a carbon copy (CC) to the Board" as in [10.2017.0](https://github.com/thewca/wca-documents/blob/master/documents/motions/10.2017.0%20-%20Committees%20and%20Teams.md)?
- ...

**Comment by cubewhiz** [comment]
Some more.

- In 4.2018.1 it says "processes that are lead by WCA Board" but it should be "led".
- In 1.2017.1, it should be a period and capital "S" for "See WCA Motion..."
