### ISSUE TITLE
Remove Silent Spring from the list of acceptable names

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#50]
The WCAT believes that a competition name based solely on the competition events leaves the name too generic (although that in combination with location, for example, leaves a more unique name). This can lead to many competition in many locations being called the same thing. For instance a competition named: "Please Be Quiet 2019". Should we just allow this name to be taken from the first delegate who wants it? It's much better to add the location to the name in these cases.

Proposal, Remove:
> Silent Spring 2017 (competition is named after the events)

**Comment by operge** [comment]
The Board agrees with removing this example as it is too generic. We also believe that perhaps it is time to suggest that locations are added to the competition names now. Not as a must but maybe as a should.

**Comment by cubewhiz** [comment]
It is probably best to rename Silent Spring 2017 instead of removing it, though. Perhaps something like "Silent Spring Atlanta 2019" or similar to emphasize the recommendation of providing a location?

**Comment by AlbertoPdRF** [comment]
That sounds good to me. I'll start a vote now.

**Comment by operge** [comment]
We voted to instead of removing the example entirely, you should rename it to include a location instead.
