### ISSUE TITLE
Update Dues System Policy to include scope for Regional Organisations

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-documents#84]
Seeing the updates to the Dues System Policy (v1.2) made me think of additional detail that could be added to the policy to reflect how WCA Dues are handled for regional organisations.

2.1 makes it clear that the paying of the dues can be done by an organisation, but it is ultimately the responsibility of the WCA Delegate(s). In practice, Speedcubing Australia Inc. is invoiced for all competitions that take place in Australia - this works extremely well as a system and suits us!

Personally, I think it would be good if the role regional organisations can play is recognised in a later version of the policy. Responsibility for payment could ultimately rest on the regional organisation itself, so long as it is recognised by the WCA and has approval by all the region's delegates to act on their behalf in financial matters.

**Comment by cubewhiz** [comment]
I think this is reasonable.

**Comment by AlbertoPdRF** [comment]
I personally prefer that the ultimate responsibility still relies on the WCA Delegate(s) of the competition.

**Comment by Ivan-Brigidano** [comment]
Just to point a different situation: in Madrid WCA Dues are usually paid by the Madrid association instead by the Spanish association. And the Officially recognized is the last one.

**Comment by Epride** [comment]
Resolved in latest update
