### ISSUE TITLE
Security: Can we restrict Travis's user to *only* being able to run `deploy.sh` on the production server?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-documents#9]
Currently, if someone compromises this repository and is able to decrypt the ssh private key, that person then is able to ssh to our production server and do *anything*.

I think it would be good to use this ssh feature: https://stackoverflow.com/questions/402615/how-to-restrict-ssh-users-to-a-predefined-set-of-commands-after-login to restrict the Travis user to only being able to run `deploy.sh` on our production server. That way if someone compromises this repo or decrypts the private key somehow, they aren't able to do much to our production server.

I think implementing this would just require adding the `commands=` bit to our authorized_keys file over in https://github.com/thewca/worldcubeassociation.org/blob/ae3c915762a8e7c7d1ea14c78d795bb91170ddbb/chef/site-cookbooks/wca/templates/gen-authorized-keys.sh.erb#L18-L23.

@jonatanklosko, does this make sense/sound reasonable? If so, I'll attempt to take care of it later this week.

**Comment by jonatanklosko** [comment]
This sounds like a good security boost!

**Comment by jfly** [comment]
@lgarron, that's an interesting idea, but I'm not sure it would actually be possible, because deploying changes requires restarting our Gunicorn rails app server, but if that process starts trying to reset itself, I'm not sure what would happen.

For now, I'm going to look into restricting our travis user a bit, but someone else is definitely welcome to look into a ssh-less solution if they are motivated!
