### ISSUE TITLE
Allow for Sub-Regional Organizations

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-documents#90]
Some organisations (e.g. Spain) recognise/list sub-regional organisations. Should something like this be added as a right of the regional organisation in the motions? If the WCA continues to grow regional organisations may play a bigger role in organising and regulating competitions within areas. If this is the case they may also want to have scope for recognising their own sub-regional organisations.

There would be lots of things to work through if this were the case. Such as, should these sub-ROs have rights and duties recognised and regulated by the WCA as well?

**Comment by Epride** [comment]
Personally I think sub-ROs should not have the same rights and responsibilities within the WCA as the ROs however there should be some sort of hierarchy system in which ROs have rights and responsibilities in their relationship with the WCA and the sub-ROs should have a similar relationship with their overarching RO. Thus the WCA recognised RO will act as a "middle-man" between the sub-RO and the WCA. I also feel there may need to be more definition as to what regions ROs can/should cover however I feel this is a discussion for another issue.

**Comment by Ivan-Brigidano** [comment]
As a president of one of this sub regional organizations of Spain I think this could be nice.
However we should have into account that even in Spain (a country with a lot of sub regional organizations) not all are as important and productive. In addition, this could crowed the Board if the number of applications is very large.
Maybe this could be a good implementation in a future, but I don't think it worth right now. I think the WCA should focuses now in encouraging new National Organizations.

**Comment by cubewhiz** [comment]
I agree that we should not put too much focus on this yet. Let's curb this until we have enough regional organizations that we feel ready to expand to another level.

**Comment by cubewhiz** [comment]
I'm closing this for now as the Board decided it is better to let national organizations recognize sub-regional organizations instead.
