### ISSUE TITLE
WRCP 10.1 - Change Early Submission

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-documents#99]
> The organization team may request to require competitors to submit puzzles at a specific time before an event is scheduled to begin.

I would suggest to change this to something like:

> The organization team may request to require competitors to submit puzzles at a specific time before an event is scheduled to begin or before the competitor is required to compete.

This would encompass times when the organization team (IMO unfairly) requires all competitors to submit cubes for a Head-to-Head final at the beginning. We can evaluate these on a case by case level to see if it is even necessary to submit early, or submit whenever the competitor is called to compete.

**Comment by cubewhiz** [comment]
I don't see what this adds. Competitors always submit their puzzles before they are required to compete.

**Comment by Jambrose777** [comment]
Maybe different wording then.

My main concern is if puzzles are required a significant amount of time before the competitor would be panned to solve. And example would be if the org team requires competitors to submit their 3x3s for a head to head final before it begins. The competitors seeded at the top will have more of a disadvantage due to the time in between their submission and solving time compared to the first competitors to compete.

**Comment by AlbertoPdRF** [comment]
I don't think that this point in the policy refers to the situation that you are describing at all, as the event is already beginning in your case, so the organization team doesn't have to "request to require competitors to submit puzzles at a specific time before an event is scheduled to begin."

**Comment by cubewhiz** [comment]
Honestly, I don't even consider this much of an issue. What is the disadvantage? A few minutes without your puzzle? I think most competitors I've seen in head-to-head formats have a warm-up cube they use  between solves anyway.

**Comment by Jambrose777** [comment]
> Honestly, I don't even consider this much of an issue. What is the disadvantage? A few minutes without your puzzle? I think most competitors I've seen in head-to-head formats have a warm-up cube they use between solves anyway.

With the duration of some head to head finals, this can mean that the cube goes untouched for possibly an hour or more. If a cube does this then it can potentially not preform at the same speeds that it otherwise would if it was turned during that hour.

**Comment by cubewhiz** [comment]
I am closing this as this doesn't seem to have much support at this time.
